# Generated by Django 5.0.2 on 2025-03-26 21:26

import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preregistro_nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_exp', models.TextField()),
                ('fch_rcp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuario', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='preregistro_nota_arch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arch', models.FileField(upload_to=documentos.models.camb_nom_arch)),
                ('cod_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.preregistro_nota')),
            ],
        ),
        migrations.CreateModel(
            name='procedencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
                ('descrip_larga', models.TextField()),
                ('cod_proced_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='documentos.procedencia')),
            ],
        ),
        migrations.AddField(
            model_name='preregistro_nota',
            name='cod_procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.procedencia'),
        ),
        migrations.AddField(
            model_name='preregistro_nota',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.usuario'),
        ),
    ]
