# Generated by Django 5.0.2 on 2025-03-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_preregistro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='preregistro_nota',
            name='cod_estado_preregistro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.estado_preregistro'),
        ),
    ]
