# Generated by Django 5.0.2 on 2025-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_estado_preregistro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro_nota_arch',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
