# Generated by Django 5.0.2 on 2025-04-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_preregistro_nota_arch_nombre_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tp_prioridad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='procesamiento_nota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch_exp', models.DateTimeField()),
                ('fch_limite', models.DateTimeField()),
                ('asunto', models.TextField()),
                ('contenido', models.TextField()),
                ('fch_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('cod_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.preregistro_nota')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.usuario')),
                ('tp_prioridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.tp_prioridad')),
            ],
        ),
    ]
