# Generated by Django 5.0.2 on 2025-08-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_tp_prioridad_procesamiento_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='tp_documentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='procesamiento_nota',
            name='disposicion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='procesamiento_nota',
            name='tp_documentacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.tp_documentacion'),
        ),
    ]
