# Generated by Django 5.0.2 on 2025-08-14 16:00

import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_tp_documentacion_procesamiento_nota_disposicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_cumplimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='notaxprocedencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Observacion', models.TextField()),
                ('cod_estado_cumplimiento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.estado_cumplimiento')),
                ('cod_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.procesamiento_nota')),
                ('cod_procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.procedencia')),
            ],
        ),
        migrations.CreateModel(
            name='evidencia_cumpli_nota_arch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arch', models.FileField(upload_to=documentos.models.camb_nom_arch)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.notaxprocedencia')),
            ],
        ),
    ]
