# Generated by Django 5.0.2 on 2025-08-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_estado_cumplimiento_notaxprocedencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaxprocedencia',
            name='Observacion',
            field=models.TextField(null=True),
        ),
    ]
