# Generated by Django 5.0.2 on 2025-08-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_alter_notaxprocedencia_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_militar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.procedencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documentos.usuario')),
            ],
        ),
    ]
