# Generated by Django 5.0.2 on 2025-08-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_alter_preregistro_nota_cod_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tp_medio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='preregistro_nota',
            name='cod_medio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.tp_medio'),
        ),
    ]
