# Generated by Django 5.0.2 on 2025-08-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_tp_medio_preregistro_nota_cod_medio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregistro_nota',
            options={'permissions': [('recepcion', 'Puede recepcionar y registrar notas')]},
        ),
    ]
