# Generated by Django 5.0.2 on 2025-08-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_alter_preregistro_nota_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preregistro_nota',
            options={'permissions': [('recepcion', 'Puede recepcionar y registrar notas'), ('procesar', 'Puede recepcionar y registrar notas'), ('aprobar', 'Puede recepcionar y registrar notas'), ('bandeja', 'Puede recepcionar y registrar notas')]},
        ),
    ]
