# Generated by Django 4.2.7 on 2025-08-18 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0014_alter_preregistro_nota_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cod_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mision',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vision',
            field=models.TextField(null=True),
        ),
    ]
