# Generated by Django 5.0.2 on 2025-08-19 17:04

import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0015_usuario_cod_user_usuario_mision_usuario_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='tp_estado_nota_env',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='notas_enviadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch_env', models.DateTimeField()),
                ('no_exp', models.TextField(null=True)),
                ('contenido', models.TextField(null=True)),
                ('recepcion', models.TextField(null=True)),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.procedencia')),
                ('tp_documentacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.tp_documentacion')),
                ('tp_medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tp_medio')),
                ('tp_estado_nota_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tp_estado_nota_env')),
            ],
            options={
                'permissions': [('registra_notas_enviadas', 'Puede gestionar las notas enviadas')],
            },
        ),
        migrations.CreateModel(
            name='nota_env_arch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arch', models.FileField(upload_to=documentos.models.camb_nom_arch_enviadas)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_nota_enviada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.notas_enviadas')),
            ],
        ),
    ]
