# Generated by Django 5.0.2 on 2025-08-19 18:17

import django.db.models.deletion
import documentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0016_tp_estado_nota_env_notas_enviadas_nota_env_arch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notas_enviadas',
            name='cod_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procesamiento_nota',
            name='cod_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='nota_env_resp_arch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arch', models.FileField(upload_to=documentos.models.camb_nom_arch_enviadas_resp)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_nota_enviada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.notas_enviadas')),
            ],
        ),
    ]
