# Generated by Django 5.0.2 on 2025-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0017_notas_enviadas_cod_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas_enviadas',
            name='completado',
            field=models.TextField(null=True),
        ),
    ]
