# Generated by Django 5.0.2 on 2025-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0018_notas_enviadas_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas_enviadas',
            name='fch_env',
            field=models.DateField(null=True),
        ),
    ]
