# Generated by Django 5.0.2 on 2025-08-22 13:05

import django.db.models.deletion
import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0019_alter_notas_enviadas_fch_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='nota_disp_arch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arch', models.FileField(upload_to=documentos.models.camb_nom_arch_enviadas)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.procesamiento_nota')),
            ],
        ),
    ]
