# Generated by Django 5.0.2 on 2025-08-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0020_nota_disp_arch'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedencia',
            name='color',
            field=models.TextField(null=True),
        ),
    ]
