# Generated by Django 5.0.2 on 2025-11-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0022_anuncio'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
