# Generated by Django 5.0.2 on 2025-11-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0023_anuncio_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro_nota',
            name='registro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
