# Generated by Django 5.0.2 on 2025-11-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0024_preregistro_nota_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedencia',
            options={'permissions': [('crear_procedencia', 'Puede solamente crear procedencias')]},
        ),
    ]
