# Generated by Django 5.0.2 on 2025-11-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0025_alter_procedencia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='color',
            field=models.TextField(null=True),
        ),
    ]
