# Generated by Django 5.0.2 on 2025-11-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0027_user_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='color',
        ),
    ]
