# Generated by Django 5.0.2 on 2025-12-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0028_remove_usuario_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='arma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField(null=True)),
                ('descrip_larga', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='grado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField(null=True)),
                ('descrip_larga', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cod_procedencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.procedencia'),
        ),
        migrations.CreateModel(
            name='firma_autorizada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_completo', models.TextField(null=True)),
                ('serie', models.TextField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cod_arma', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.arma')),
                ('cod_procedencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.procedencia')),
                ('cod_grado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documentos.grado')),
            ],
        ),
    ]
