# Generated by Django 5.0.2 on 2025-12-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0029_arma_grado_usuario_cod_procedencia_firma_autorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma_autorizada',
            name='cargo_segun_firma',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='grado',
            name='dem',
            field=models.BooleanField(default=True),
        ),
    ]
