# Generated by Django 5.0.2 on 2025-12-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0030_firma_autorizada_cargo_segun_firma_grado_dem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='dem',
        ),
        migrations.AddField(
            model_name='firma_autorizada',
            name='diplomado',
            field=models.TextField(null=True),
        ),
    ]
