# Generated by Django 5.0.2 on 2025-12-10 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0031_remove_grado_dem_firma_autorizada_diplomado'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma_autorizada',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
