# Generated by Django 5.0.2 on 2025-12-11 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0032_firma_autorizada_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamiento_nota',
            name='cod_firma_autorizada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.firma_autorizada'),
        ),
    ]
